---
- hosts: localhost
  vars:
    state: present
    s3_bucket: fatih-terraform-backup
    key: terraform.tfstate
    region: us-east-1
    app_env: dev

  tasks:
  - name: Run terraform scripts
    terraform:
      project_path: "./"
      state: "{{ state }}"
      force_init: true
      backend_config:
        region: "{{ region }}"
        bucket: "{{ s3_bucket }}"
        key: "{{ key }}"
      variables_files: "{{ app_env }}.tfvars"
      workspace: "{{ app_env }}"