---
- hosts: localhost
  vars:
    state: present
    app_env: dev

  tasks:
  - name: Run terraform scripts
    terraform:
      project_path: "./"
      state: "{{ state }}"
      force_init: true
      backend_config_files: backend_config.tf
      variables_files: "{{ app_env }}.tfvars"
      workspace: "{{ app_env }}"