--- 
- hosts: localhost 
  become: yes
  become_method: su
  become_user: ec2-user
  tasks:
  - name: Install boto3
    pip:
      name: boto3
      state: present

  - name: Create S3 bucket
    s3_bucket:
      name: fatih-terraform-backup1
      state: present