--- 
- hosts: localhost 
  tasks:
  - name: Install boto3
    pip:
      name: boto3
      state: present
    become: yes

  - name: Create S3 bucket
    s3_bucket:
      name: fatih-terraform-backup2
      state: present
    become: yes