--- 
- hosts: localhost 
  vars:
    state: present
    s3_bucket: fatih-terraform-backup
    key: terraform.tfstate
    region: us-east-1
    
  tasks:
  - name: Install boto3
    pip:
      name: 
      - boto3
      - botocore
      state: "{{ state }}"
    become: yes

  #- name: Install boto
  #  pip:
  #    name: boto
  #    state: present
  #  become: yes

  - name: Create S3 bucket
    s3_bucket:
      name: "{{ s3_bucket }}"
      state: "{{ state }}"
      region: "{{ region }}"
    become: yes

  - name: Create dynamo table with primary key
    dynamodb_table:
      name: tf-backup
      region: "{{ region }}"
      state: "{{ state }}"
      hash_key_name: LockID
      hash_key_type: STRING
      read_capacity: 2
      write_capacity: 2

  
